[sigma_sysmon]
definition = index=win_sysmon
iseval = 0

[sigma_win_security]
definition = index=win_security
iseval = 0

[sigma_powershell_classic]
definition = index=win_powershell LogName="Windows Powershell"
iseval = 0

[sigma_powershell]
definition = index=win_powershell LogName="Microsoft-Windows-PowerShell/Operational"
iseval = 0
